# NumPy


## NumPy란

* 수치해석용 Python 라이브러리
 * C로 구현 (파이썬용 C라이브러리)
 * BLAS/LAPACK 기반
 * 빠른 수치 계산을 위한 Structured Array 제공
* Home
 * http://www.numpy.org/
* Documentation
 * http://docs.scipy.org/doc/
* Tutorial
 * http://www.scipy-lectures.org/intro/numpy/index.html
 * https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

## NumPy Array

In [1]:
import numpy as np
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

### Python List vs NumPy Array 

* Python List
 * 여러가지 타입의 원소
 * 메모리 용량이 크고 속도가 느림
 * nesting 가능
 * 전체 연산 불가
* NumPy Array
 * 동일 타입의 원소
 * 메모리 최적화, 계산 속도 향상
 * 크기(dimension)이 명확하게 정의 
 * 전체 연산 가능

In [2]:
L = range(1000)
%timeit [i**2 for i in L]

10000 loops, best of 3: 138 µs per loop


In [3]:
a = np.arange(1000)
%timeit a**2

The slowest run took 19.28 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.29 µs per loop


In [4]:
L = range(3)
L

[0, 1, 2]

In [5]:
L * 2

[0, 1, 2, 0, 1, 2]

In [6]:
[i * 2 for i in L]

[0, 2, 4]

In [8]:
a = np.arange(3)
a

array([0, 1, 2])

In [9]:
a * 2

array([0, 2, 4])

### Create Array (1D)

In [10]:
a = np.array([0,1,2,3])

In [11]:
a.ndim

1

In [12]:
a.shape

(4L,)

In [13]:
len(a)

4

### Create Array (2D)

In [14]:
b = np.array([[0,1,2],[3,4,5]])    # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2L, 3L)

In [17]:
len(b)

2

In [18]:
a2 = np.array([[0,1,2,3]]).T
a2

array([[0],
       [1],
       [2],
       [3]])

In [19]:
a3 = np.array([[0], [1], [2], [3]])
a3

array([[0],
       [1],
       [2],
       [3]])

In [20]:
a2.shape, a3.shape

((4L, 1L), (4L, 1L))

### Create Array (3D)

In [22]:
c = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
c.ndim, c.shape

(3, (2L, 2L, 2L))

In [25]:
len(c)

2

### 1 dim vs 2 dim

In [26]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [27]:
a.shape

(4L,)

In [31]:
b = np.array([[0,1,2,3]])
b

array([[0, 1, 2, 3]])

In [32]:
b.shape

(1L, 4L)

In [33]:
c = np.array([[0], [1], [2], [3]])
c

array([[0],
       [1],
       [2],
       [3]])

In [34]:
c.shape

(4L, 1L)

### Transpose


In [35]:
a = np.array([[0,1,2,3]])
a

array([[0, 1, 2, 3]])

In [36]:
a.shape

(1L, 4L)

In [39]:
b = a.T
b

array([[0],
       [1],
       [2],
       [3]])

In [38]:
b.shape

(4L, 1L)

### Array Creation Functions

* `arange`
* `linspace`, `logspace`
* `zeros`, `ones`
* `rand`, `randn`
* `tile`

In [40]:
a = np.arange(10)   # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
b = np.arange(1, 9, 2)   # start, end (exclusive), step
b

array([1, 3, 5, 7])

In [42]:
c = np.linspace(0, 1, 6) # start, end, num-points
c

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [45]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [46]:
a = np.ones((3, 3))   # reminder: (3, 3) is a tuple
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [48]:
b = np.zeros((2,2))
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [49]:
c = np.diag([1,2,3])
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [50]:
d = np.eye(4)
d

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [51]:
a = np.array([0,1,2])
a

array([0, 1, 2])

In [52]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [61]:
np.tile(a, (3,2)), (np.tile(a, (3,2))).ndim, (np.tile(a, (3,2))).shape

(array([[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]]), 2, (3L, 6L))

In [60]:
np.tile(a, (2,1,2)), np.tile(a, (2,1,2)).ndim, np.tile(a, (2,1,2)).shape

(array([[[0, 1, 2, 0, 1, 2]],
 
        [[0, 1, 2, 0, 1, 2]]]), 3, (2L, 1L, 6L))

In [62]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [63]:
b.shape

(2L, 2L)

In [64]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [65]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### Shape Change

* `reshape`
* `flatten`, `ravel`

In [66]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
b = np.reshape(a, (4,5))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
c = np.reshape(b, (5,4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [70]:
d = a.reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

* 인수가 -1 
 * numpy가 나머지 인수들을 이용하여 사이즈를 맞춘다.

In [71]:
a = np.arange(24)
a.reshape(2, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [72]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [73]:
a.reshape(-1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [74]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [79]:
d = c.flatten() # return a copy
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
d.base is None

True

In [81]:
e = c.ravel()
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
e.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Stack
* hstack
* vstack
* dstack

In [83]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [84]:
np.vstack([a * 10, a * 20])

array([[ 0, 10, 20, 30, 40],
       [ 0, 20, 40, 60, 80]])

In [85]:
b = np.arange(5)[:, np.newaxis]
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [86]:
np.hstack([b * 10, b * 20])

array([[ 0,  0],
       [10, 20],
       [20, 40],
       [30, 60],
       [40, 80]])

In [87]:
a = np.array((1,2,3))
b = np.array((2,3,4))

In [88]:
a, a.shape

(array([1, 2, 3]), (3L,))

In [89]:
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [91]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

### dtype
* `bool`	Boolean (True or False) stored as a byte
* `int8`	Byte (-128 to 127)
* `int16`	Integer (-32768 to 32767)
* `int32`	Integer (-2147483648 to 2147483647)
* `int64`	Integer (-9223372036854775808 to 9223372036854775807)
* `uint8`	Unsigned integer (0 to 255)
* `uint16`	Unsigned integer (0 to 65535)
* `uint32`	Unsigned integer (0 to 4294967295)
* `uint64`	Unsigned integer (0 to 18446744073709551615)
* `float16`	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
* `float32`	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
* `float64`	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
* `S`  String

In [92]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [93]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

In [94]:
c = np.array([1,2,3], dtype=np.float64)
c.dtype

dtype('float64')

In [95]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

In [96]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

In [97]:
f = np.array(['Bonjour', 'Hello', 'Hallo',])
f.dtype

dtype('S7')

* `NaN`     Not a Number
* `Inf`     Infinity

In [100]:
x = np.array([-1, 1, 0]) / np.array([0, 0, 0])   #Python 2.7 version
x

array([0, 0, 0])

In [75]:
x = np.array([1, -1, 0]) / np.array([0, 0, 0])   #3. version
x

array([ inf, -inf,  nan])

In [76]:
x[0]

inf

In [101]:
np.inf, np.nan

(inf, nan)

### Indexing

In [102]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a[0], a[2], a[-1]

(0, 2, 9)

In [104]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multi-dimensional Indexing

In [105]:
l = [[0,0,0], [0,1,0], [0,0,2]]
l[1]

[0, 1, 0]

In [106]:
l[1][1]

1

In [107]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [108]:
a[1, 1]

1

In [109]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [110]:
a[2] = [10, 20, 30]
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [10, 20, 30]])

### Slicing

In [111]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a[2:9:3]

array([2, 5, 8])

In [113]:
a[:4]

array([0, 1, 2, 3])

In [114]:
a[1:3]

array([1, 2])

In [115]:
a[::2]

array([0, 2, 4, 6, 8])

In [116]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

### Multi-dimensional Slicing

In [117]:
a = np.arange(6) + (np.arange(6) * 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [118]:
a[0, :]

array([0, 1, 2, 3, 4, 5])

In [119]:
a[:, 0]

array([ 0, 10, 20, 30, 40, 50])

<img src="http://www.scipy-lectures.org/_images/numpy_indexing.png" style="width:70%; margin: 0 auto 0 auto;">

### newaxis
* 차원 확장

In [120]:
a = np.arange(4)
a, a.shape

(array([0, 1, 2, 3]), (4L,))

In [123]:
b = np.arange(4).reshape(4,1)
b, b.shape

(array([[0],
        [1],
        [2],
        [3]]), (4L, 1L))

In [124]:
c = np.arange(4)[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3]])

In [125]:
c.shape

(4L, 1L)

### View

* A slicing operation creates a view on the original array, which is just a way of accessing array data. 
* Thus the original array is not copied in memory. 

In [126]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [128]:
a[0] = 99
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [129]:
b

array([99,  2,  4,  6,  8])

### Copy

In [130]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [131]:
b = a.copy()
b

array([0, 1, 2, 3, 4])

In [132]:
a[0] = 99
a

array([99,  1,  2,  3,  4])

In [133]:
b

array([0, 1, 2, 3, 4])

### Fancy indexing 팬시 인덱싱
* Boolean Fancy Indexing
 * True인 원소만 선택 
 * 크기가 같아야 한다.
* list
 * 또는 tuple, or array
 * 지정된 인덱스만 선택
 * 크기가 달라도 된다.
* multi dimension에도 사용 가능
* create copy, not view

In [134]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [135]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [136]:
idx = (a % 2) == 0
idx

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False], dtype=bool)

In [137]:
a[idx]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [138]:
a[(a % 2) == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [139]:
a = np.arange(50) * 10
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490])

In [140]:
idx = [1, 3, 4, -1, 30]
a[idx]

array([ 10,  30,  40, 490, 300])

In [141]:
a[[1,3,4,-1,30]]

array([ 10,  30,  40, 490, 300])

In [143]:
a = np.arange(6) + (np.arange(6) * 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [144]:
a[[0,1,2,3,4],(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [145]:
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

## Array Operation

### Elementwise operations

In [146]:
a = np.array([1,2,4,5])
a

array([1, 2, 4, 5])

In [147]:
a + 1

array([2, 3, 5, 6])

In [148]:
2**a

array([ 2,  4, 16, 32])

In [149]:
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [150]:
a - b

array([-1.,  0.,  2.,  3.])

In [151]:
a + b

array([ 3.,  4.,  6.,  7.])

In [152]:
c = np.ones((3,3))
c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [153]:
c * c # element-wise, NOT Matrix product

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [154]:
c.dot(c)   # matrix product

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [155]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [156]:
a == b

array([False,  True, False,  True], dtype=bool)

In [157]:
a > b

array([False, False,  True, False], dtype=bool)

In [158]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [159]:
np.array_equal(a,b)

False

In [160]:
np.array_equal(a,c)

True

In [161]:
a = np.arange(5)

In [162]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [163]:
np.log(a)

array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [164]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [165]:
np.log10(a)

array([       -inf,  0.        ,  0.30103   ,  0.47712125,  0.60205999])

In [166]:
a = np.arange(4)
b = np.array([1,2])
a, b

(array([0, 1, 2, 3]), array([1, 2]))

In [167]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### Dimension Reduction Operation

* sum
* min, max, argmin, argmax
* mean, median, std, var
* all, any

In [168]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [169]:
np.sum(x)

10

In [170]:
x.sum()

10

In [172]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

<img src="http://www.scipy-lectures.org/_images/reductions.png", style="width: 20%; margin: 0 auto 0 auto;">

In [173]:
x.sum()

6

In [175]:
x.sum(axis=0)   # columns (first dimension)

array([3, 3])

In [176]:
x.sum(axis=1)   # rows (second dimension)

array([2, 4])

In [177]:
x = np.array([1, 3, 2])

In [178]:
x.min()

1

In [179]:
x.max()

3

In [180]:
x.argmin()  # index of minimum

0

In [181]:
x.argmax()  # index of maximum

1

In [182]:
np.all([True, True, False])

False

In [183]:
np.any([True, True, False])

True

In [184]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [185]:
np.any(a != 0)

False

In [186]:
np.all(a == a)

True

In [187]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [188]:
((a <= b) & (b <= c)).all()

True

In [189]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [190]:
x.mean()

1.75

In [191]:
np.median(x)

1.5

In [197]:
np.median(y, axis=-1) # last axis

array([ 2.,  5.])

In [193]:
x.std()          # full population standard dev.

0.82915619758884995

### Broadcasting

<img src="http://www.scipy-lectures.org/_images/numpy_broadcasting.png" style="width: 60%; margin: 0 auto 0 auto;">

In [198]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [199]:
np.tile(np.arange(0, 40, 10), (3, 1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [200]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [201]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [202]:
a[:, 0][:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30]])

In [203]:
a[:, 0][:, np.newaxis] + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [204]:
a = np.ones((4, 5))
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [205]:
a[0]

array([ 1.,  1.,  1.,  1.,  1.])

In [206]:
a[0] = 2
a

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [207]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]

In [209]:
x

array([0, 1, 2, 3, 4])

In [210]:
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [211]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425]])

### ogrid, mgrid, meshgrid

In [212]:
x, y = np.ogrid[0:3, 0:5]

In [213]:
x

array([[0],
       [1],
       [2]])

In [214]:
y

array([[0, 1, 2, 3, 4]])

In [215]:
np.ogrid[-1:1:3j, -1:1:5j]

[array([[-1.],
        [ 0.],
        [ 1.]]), array([[-1. , -0.5,  0. ,  0.5,  1. ]])]

In [217]:
x, y = np.mgrid[0:3, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [218]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [219]:
np.mgrid[-1:1:3j, -1:1:5j]

array([[[-1. , -1. , -1. , -1. , -1. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ],
        [ 1. ,  1. ,  1. ,  1. ,  1. ]],

       [[-1. , -0.5,  0. ,  0.5,  1. ],
        [-1. , -0.5,  0. ,  0.5,  1. ],
        [-1. , -0.5,  0. ,  0.5,  1. ]]])

In [220]:
X, Y = np.meshgrid(np.arange(3), np.arange(5))
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [222]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [223]:
zip(X.ravel(), Y.ravel())

[(0, 0),
 (1, 0),
 (2, 0),
 (0, 1),
 (1, 1),
 (2, 1),
 (0, 2),
 (1, 2),
 (2, 2),
 (0, 3),
 (1, 3),
 (2, 3),
 (0, 4),
 (1, 4),
 (2, 4)]

In [225]:
plt.scatter(*np.vstack(np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-2, 2, 10))).reshape(2,-1).tolist())

### sort

In [226]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [227]:
a[:, 0]

array([4, 1])

In [228]:
b = np.sort(a, axis=0)
b

array([[1, 2, 1],
       [4, 3, 5]])

In [229]:
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [230]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [231]:
a[j]

array([1, 2, 3, 4])

## Array용 수학 함수

* universal function 
 * 빠른 element-wise (vectorized) 연산
* 모든 NumPy/Scipy 수학 함수는 자동으로 vectorized 연산 수행

In [232]:
x = range(10)
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [233]:
import math
math.exp(x)

TypeError: a float is required

In [234]:
math.exp(x[0])

1.0

In [235]:
[math.exp(x_i) for x_i in x]

[1.0,
 2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236,
 148.4131591025766,
 403.4287934927351,
 1096.6331584284585,
 2980.9579870417283,
 8103.083927575384]

In [236]:
np.exp(x)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

## Random Number

### `numpy.random` 서브패키지

* `seed`: pseudo random 상태 설정
* `shuffle`: 조합(combination)
* `choice`: 순열(permutation) 및 조합(combination)
* `rand`: uniform 
* `random_integers`: uniform integer
* `randn`: Gaussina normal



#### seed

* 컴퓨터의 랜덤 생성은 사실 랜덤이 아니다.
* 랜덤처럼 보이지만 정해진 알고리즘에 의해 생성되는 규칙적인 순열
* 시작점이 정해지면 랜덤 함수를 사용해도 정해진 숫자가 나온다.

In [249]:
np.random.seed(0)

* `numpy.random.shuffle(x)`
 * Parameters:	
    * x : array_like
        * The array or list to be shuffled.

In [251]:
x = np.arange(10)
np.random.shuffle(x)
x

array([3, 5, 1, 2, 9, 8, 0, 6, 7, 4])

* `numpy.random.choice(a, size=None, replace=True, p=None)`
 * Parameters:	
    * a : 1-D array-like or int
        * If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if a was np.arange(n)
    * size : int or tuple of ints, optional
        * Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
    * replace : boolean, optional
        * Whether the sample is with or without replacement
    * p : 1-D array-like, optional
        * The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution over all entries in a.
 * Returns:	
    * samples : 1-D ndarray, shape (size,)
        * The generated random samples

In [252]:
# same as shuffle
np.random.choice(5, 5, replace=False)

array([4, 2, 3, 1, 0])

In [255]:
np.random.choice(5, 3, replace=False)

array([3, 1, 4])

In [259]:
np.random.choice(5, 10)

array([1, 4, 1, 2, 2, 0, 1, 1, 1, 1])

In [260]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 2, 2, 2, 2, 3, 3, 3, 2], dtype=int64)

In [268]:
import seaborn as sns

In [275]:
x = np.random.rand(10000)
print(x[:10])
sns.distplot(x)
plt.show();

[ 0.64200039  0.27084382  0.62092388  0.06183395  0.87730951  0.19074982
  0.57133725  0.25045934  0.50776487  0.34434946]


In [270]:
np.random.rand(3, 2)

array([[ 0.76299996,  0.25428196],
       [ 0.97005498,  0.80007457],
       [ 0.62622565,  0.14620928]])

In [276]:
x = np.random.random_integers(-100, 100, 50)
sns.distplot(x, rug=True)
plt.show();

C:\Anaconda3\envs\py27\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(-100, 100 + 1) instead
  if __name__ == '__main__':


In [277]:
x = np.random.randn(1000)
sns.distplot(x, rug=True)
plt.show();

In [278]:
np.random.randn(3,4)

array([[ 0.00382468,  2.08180305,  0.43086394, -0.13132649],
       [ 0.47368239,  0.42405584, -1.69313359, -2.68433454],
       [-0.83348264, -1.32016905, -0.68569224,  0.34504914]])

#### random number count

* discrete values
 * `unique()`
 * `bincount()`
* continuous values
 * `histogram()`

In [279]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [280]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [281]:
a = np.array(['a', 'b', 'c', 'b', 'a'])
index, count = np.unique(a, return_counts=True)

In [282]:
index

array(['a', 'b', 'c'], 
      dtype='|S1')

In [283]:
count

array([2, 2, 1], dtype=int64)

In [284]:
np.bincount([1, 1, 2, 2, 3, 3, 3], minlength=6)

array([0, 2, 2, 3, 0, 0], dtype=int64)

In [285]:
np.histogram([1.1, 2.5, 1.8, 2.4, 0.7], bins=[0, 1, 2, 3])

(array([1, 2, 2], dtype=int64), array([0, 1, 2, 3]))

In [286]:
np.histogram([1, 2, 1], bins=[0, 1, 2, 3])

(array([0, 2, 1], dtype=int64), array([0, 1, 2, 3]))

In [287]:
np.histogram([[1, 2, 1], [1, 0, 1]], bins=[0, 1, 2, 3])

(array([1, 4, 1], dtype=int64), array([0, 1, 2, 3]))

In [288]:
np.histogram(np.arange(4), bins=np.arange(5), density=True)

(array([ 0.25,  0.25,  0.25,  0.25]), array([0, 1, 2, 3, 4]))